#!/bin/zsh -f

local -a args
local pattern files

for arg; do
  case "$arg" in

    (-*)
      # Don't need to do anything with options
      ;;

    (*)
      # First non-option argument is assumed to be the pattern
      if [[ -z $pattern ]]; then
	pattern=$arg
	# Remove "\zs" from argument for ack, it's for vim
	arg=${arg/\\zs}
      fi
      ;;

  esac

  args=($args $arg)
done

files=$(ack -l --print0 "${(@)args}")

if [[ -n $files ]]; then
  vim "+/$pattern" ${(0)files}
else
  echo "No matching files"
  return 1
fi
