# To be used by `brew bundle`

brew "tmux"
brew "neovim"
brew "reattach-to-user-namespace"
cask "kitty"
brew "mas"
brew "coreutils"
brew "gnupg"
brew "bash"
brew "direnv"
brew "httpie"
brew "entr"
brew "ripgrep"
brew "fzf"
brew "git"
brew "the_silver_searcher"
brew "ruby-build"
brew "try"
brew "gh"
brew "glab"
brew "yq"

if File.directory? "#{ENV['HOME']}/vc/oss/git"
  brew "rust"
  brew "asciidoc"
  brew "xmlto"
end

cask "secretive"
cask "karabiner-elements"
cask "docker-desktop"
cask "witch"
cask "spotify"
cask "zoom"
cask "microsoft-teams"
cask "visual-studio-code"
cask "codex"
cask "t3-code"
cask "polypane"

mas "BitWarden", id: 1352778147
