#!/usr/bin/env perl

use strict;
use warnings;
use Cwd;

my $dir;
my $progdir = $0;
$progdir =~ s{/[^/]+$}{};

my $pwd = getcwd;
if( $pwd eq $ENV{HOME} ) {
  $dir = $progdir;
  $dir =~ s{^\./}{};
}
elsif( $progdir eq '.' or $progdir eq $pwd) {
  $dir = $pwd;
}
else {
  die "Run from home or VC directory";
}

$dir =~ s#^$ENV{HOME}/##;

foreach my $f (@ARGV) {
  next if $f =~ /dot_setup/;
  if( $f =~ /USUAL/ ) {
    my $file = "$ENV{HOME}/$dir/USUAL";
    open FH, '<', $file or die "Can't open $file: $!\n";
    while( <FH> ) {
      chomp;
      push @ARGV, $_;
    }
    next;
  }

  my $dest = "$ENV{HOME}/.$f";
  if( -e $dest ) {
    print ". $f\n";
  }
  else {
    print "+ $f\n";
    symlink "$dir/$f" => $dest or die;
  }
}
