#!/bin/sh -e

if [ ! -r dot_setup ]; then
  echo "Not in dotfiles directory" >&2
  exit 1
fi

export GIT_CONFIG_PARAMETERS="'submodule.fetchJobs=9'"
#git submodule init
git submodule sync
git submodule update --init --recursive
vim -c:Helptags -c:q /dev/null

echo complete
