#!/bin/sh

dotfiles=$(dirname $(readlink -f ${BASH_SOURCE-$HOME/.xsessionrc}))

export GTK_IM_MODULE=xim
export PYTHONPATH="$HOME/.python"

if ! gpg-agent 2> /dev/null
then
	gpg-agent --daemon \
		--enable-ssh-support \
		--write-env-file ~/.gpg-agent.info

	. ~/.gpg-agent.info
	export GPG_AGENT_INFO
	export SSH_AUTH_SOCK
fi

[ -r ~/.touchpad.sh ] && . ~/.touchpad.sh
[ -r ~/.xmodmaprc ] && xmodmap ~/.xmodmaprc

case "$1" in
	i3)
		if type xss-lock > /dev/null; then
			xset s 60
			xss-lock -n $dotfiles/xss-lock/dim-screen -l $dotfiles/xss-lock/transfer-sleep-lock-i3lock &
		else
			xautolock -time 5 -locker i3lock &
		fi
		nm-applet &
		xfce4-power-manager &
		xsetroot -gray
		;;
esac

[ -x ~/.dropbox-dist/dropbox ] && ~/.dropbox-dist/dropbox &
[ -r ~/.synergy.conf ] && synergys
[ -r ~/.config/touchegg/touchegg.conf ] && touchegg >&/dev/null &

unclutter -idle 5 -root -noevents &
