#!/bin/zsh

hostname=$(hostname)

. ~/.zsh.d/functions/update_env_from_tmux
update_env_from_tmux

case "$1" in
  (qqx)
    pat='(pug*|milamber*)'
    ssh_host='pug.qqx.org'
    ;;
  (trilug)
    pat='(pilot*)'
    ssh_host='pilot.trilug.org'
    ;;
esac

[[ $hostname != ${~pat} ]] && ssh=(ssh $ssh_host)

$ssh /usr/lib/dovecot/imap

# For some reason dovecot is exiting with code 81
# even when there are no problems.
# This causes mutt to pause to tell me that when closing the connection.
# Ignore that specific exit code.
st=$?
[ $st = 81 ] && exit 0
exit $st
