#!/bin/sh

hostname=$(hostname)

case "$1" in
  (qqx)
    case "$hostname" in
        (pug*|milamber*)
            ;;
        (*)
            ssh=pug.qqx.org
            ;;
    esac
    ;;
  (trilug)
    case "$hostname" in
      (pilot*)
        ;;
      (*)
        ssh=pilot.trilug.org
        ;;
    esac
    ;;
esac

[ -n "$ssh" ] && ssh="ssh $ssh"

$ssh /usr/lib/dovecot/imap

# For some reason dovecot is exiting with code 81
# even when there are no problems.
# This causes mutt to pause to tell me that when closing the connection.
# Ignore that specific exit code.
if [ $? = 81 ]; then
	exit 0
fi

exit $?
