#!/bin/sh

# Generate a personal terminfo entry for the supplied terminal (or $TERM)
# making the following changes:
# * disable attributes for switching to the alternate screen
# * declare that terminal supports 256 colors

term=${1:-$TERM}

[ -d $TERMINFO ] || mkdir $TERMINFO

for dir in /etc/terminfo /lib/terminfo /usr/share/terminfo /usr/share/lib/terminfo
do
	if infocmp -A $dir $term > /dev/null 2>&1
	then
		tmp=$(mktemp -d terminfo.XXXXX)
		infocmp -1 -A $dir $term | sed \
			-e '/^[ 	]*[sr]mcup=/d' \
			-e '/\(^[ 	]*colors\)#[0-9]*/s//\1#256/' \
			> $tmp/$term
		tic $tmp/$term
		rm -rf $tmp
		exit
	fi
done
