#!/bin/bash
set -ueo pipefail

die () {
  echo "$*" >&2
  exit 1
}

deb-install() {
  local pkg=$1
  dpkg -l $pkg | grep -qi '^i' || sudo apt install $pkg
}

venv() (
  root="$1"
  shift

  pybin="${root}/bin/python3"
  if ! [ -x "$pybin" ]; then
    py=$(python3 --version)
    py=${py#* }
    py=${py%.*}

    if [[ -r /etc/debian_version ]]; then
      deb-install "python${py}-venv"
    fi

    python3 -m venv "$root"
  fi

  source "${root}/bin/activate"

  local mod
  for mod in "$@"
  do
    pip3 install "$mod"
  done
)

venv ~/.local/venv/nvim pynvim
