#!/bin/sh
if ! git config user.email > /dev/null
then
  # shellcheck disable=SC2016
  echo 'Set email address with `git config user.email` first' >&2
  exit 1
fi

if [ "$(git config --type=bool --default=no commit.allowedOnMain)" = false ]
then
  ref=$(git symbolic-ref HEAD)

  # Allow initial commit to main branch
  if git rev-parse "$ref" >/dev/null 2>&1
  then
    case "$ref" in
      refs/heads/master|refs/heads/main)
        echo "Create a new branch before committing, or set commit.allowedOnMain" >&2
        exit 1
        ;;
    esac
  fi
fi
