#!/bin/sh
if ! git config user.email > /dev/null
then
  # shellcheck disable=SC2016
  echo 'Set email address with `git config user.email` first' >&2
  exit 1
fi

if [ "$(git config --type=bool --default=no commit.allowedOnMain)" = false ]
then
  ref=$(git symbolic-ref -q HEAD)
  if [ -z "$ref" ]; then
    echo "You appear to be working with a detached HEAD." >&2
    exit
  fi

  default=$(git rev-parse --verify --symbolic-full-name origin/HEAD 2>/dev/null || :)
  if [ "$default" = "" ]; then
    default=refs/heads/$(git config init.defaultbranch || echo master)
  else
    default=$(echo "$default" | sed s,remotes/origin,heads, )
  fi

  # Allow initial commit to main branch
  if git rev-parse "$ref" >/dev/null 2>&1
  then
    case "$ref" in
      "$default")
        echo "Create a new branch before committing, or set commit.allowedOnMain" >&2
        exit 1
        ;;
    esac
  fi
fi
